In [ ]:
# Drive mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import os   # To define or read path of file and directory
from skimage.io import imread  # used for reading images
from sklearn.model_selection import train_test_split
from skimage.transform import resize  # to bring all images into same size

In [ ]:
# To list all contents inside the data folder
os.listdir('/content/drive/MyDrive/Data')

['Cat', 'Dog', 'python-for-everybody.pdf']

In [ ]:
os.listdir('/content/drive/MyDrive/Data/Cat')

['cat.102.jpg',
 'cat.110.jpg',
 'cat.100.jpg',
 'cat.108.jpg',
 'cat.101.jpg',
 'cat.105.jpg',
 'cat.109.jpg',
 'cat.111.jpg',
 'cat.103.jpg',
 'cat.104.jpg',
 'cat.107.jpg',
 'cat.106.jpg',
 'cat.115.jpg',
 'cat.113.jpg',
 'cat.118.jpg',
 'cat.116.jpg',
 'cat.112.jpg',
 'cat.117.jpg',
 'cat.119.jpg',
 'cat.114.jpg',
 'cat.58.jpg',
 'cat.36.jpg',
 'cat.37.jpg',
 'cat.44.jpg',
 'cat.39.jpg',
 'cat.60.jpg',
 'cat.51.jpg',
 'cat.38.jpg',
 'cat.63.jpg',
 'cat.45.jpg',
 'cat.54.jpg',
 'cat.59.jpg',
 'cat.40.jpg',
 'cat.56.jpg',
 'cat.62.jpg',
 'cat.48.jpg',
 'cat.53.jpg',
 'cat.50.jpg',
 'cat.52.jpg',
 'cat.43.jpg',
 'cat.55.jpg',
 'cat.47.jpg',
 'cat.42.jpg',
 'cat.61.jpg',
 'cat.35.jpg',
 'cat.41.jpg',
 'cat.57.jpg',
 'cat.49.jpg',
 'cat.46.jpg',
 'cat.82.jpg',
 'cat.92.jpg',
 'cat.88.jpg',
 'cat.97.jpg',
 'cat.76.jpg',
 'cat.79.jpg',
 'cat.74.jpg',
 'cat.83.jpg',
 'cat.89.jpg',
 'cat.98.jpg',
 'cat.87.jpg',
 'cat.95.jpg',
 'cat.84.jpg',
 'cat.86.jpg',
 'cat.77.jpg',
 'cat.96.jpg',
 'cat

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Cat'))

85

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Dog'))

68

In [ ]:
# To assign path to a variable
catpath=os.path.join('/content/drive/MyDrive/Data','Cat')
for img in os.listdir(catpath):
  print(img)

cat.102.jpg
cat.110.jpg
cat.100.jpg
cat.108.jpg
cat.101.jpg
cat.105.jpg
cat.109.jpg
cat.111.jpg
cat.103.jpg
cat.104.jpg
cat.107.jpg
cat.106.jpg
cat.115.jpg
cat.113.jpg
cat.118.jpg
cat.116.jpg
cat.112.jpg
cat.117.jpg
cat.119.jpg
cat.114.jpg
cat.58.jpg
cat.36.jpg
cat.37.jpg
cat.44.jpg
cat.39.jpg
cat.60.jpg
cat.51.jpg
cat.38.jpg
cat.63.jpg
cat.45.jpg
cat.54.jpg
cat.59.jpg
cat.40.jpg
cat.56.jpg
cat.62.jpg
cat.48.jpg
cat.53.jpg
cat.50.jpg
cat.52.jpg
cat.43.jpg
cat.55.jpg
cat.47.jpg
cat.42.jpg
cat.61.jpg
cat.35.jpg
cat.41.jpg
cat.57.jpg
cat.49.jpg
cat.46.jpg
cat.82.jpg
cat.92.jpg
cat.88.jpg
cat.97.jpg
cat.76.jpg
cat.79.jpg
cat.74.jpg
cat.83.jpg
cat.89.jpg
cat.98.jpg
cat.87.jpg
cat.95.jpg
cat.84.jpg
cat.86.jpg
cat.77.jpg
cat.96.jpg
cat.75.jpg
cat.67.jpg
cat.72.jpg
cat.91.jpg
cat.69.jpg
cat.65.jpg
cat.85.jpg
cat.94.jpg
cat.78.jpg
cat.66.jpg
cat.93.jpg
cat.71.jpg
cat.64.jpg
cat.73.jpg
cat.70.jpg
cat.90.jpg
cat.68.jpg
cat.81.jpg
cat.99.jpg
cat.80.jpg


In [ ]:
dogpath=os.path.join('/content/drive/MyDrive/Data','Dog')
for img in os.listdir(dogpath):
  print(img)

dog.14.jpg
dog.13.jpg
dog.1.jpg
dog.15.jpg
dog.12.jpg
dog.10.jpg
dog.11.jpg
dog.21.jpg
dog.19.jpg
dog.23.jpg
dog.17.jpg
dog.2.jpg
dog.22.jpg
dog.16.jpg
dog.24.jpg
dog.18.jpg
dog.20.jpg
dog.3.jpg
dog.28.jpg
dog.25.jpg
dog.33.jpg
dog.32.jpg
dog.26.jpg
dog.31.jpg
dog.30.jpg
dog.27.jpg
dog.29.jpg
dog.47.jpg
dog.45.jpg
dog.43.jpg
dog.46.jpg
dog.51.jpg
dog.52.jpg
dog.60.jpg
dog.34.jpg
dog.57.jpg
dog.54.jpg
dog.48.jpg
dog.38.jpg
dog.55.jpg
dog.44.jpg
dog.41.jpg
dog.35.jpg
dog.40.jpg
dog.59.jpg
dog.6.jpg
dog.53.jpg
dog.56.jpg
dog.36.jpg
dog.58.jpg
dog.37.jpg
dog.39.jpg
dog.50.jpg
dog.5.jpg
dog.49.jpg
dog.42.jpg
dog.4.jpg
dog.66.jpg
dog.63.jpg
dog.61.jpg
dog.9.jpg
dog.68.jpg
dog.65.jpg
dog.7.jpg
dog.67.jpg
dog.8.jpg
dog.64.jpg
dog.62.jpg


In [ ]:
flat_data_arr=[]   # used for collecting input data
target_arr=[]      # used for collecting output data
categories=['Cat','Dog']
datadir='/content/drive/MyDrive/Data'    # for collecting the path of data

In [ ]:
for i in categories:                    # cat
  print('Loading categories....')       # cat
  path=os.path.join(datadir,i)          # assinging to a variable 'path'  (/content/drive/MyDrive/Data,cat)
  for img in os.listdir(path):               # collecting each images
    img_arr=imread(os.path.join(path,img))      # to read images
    img_resize=resize(img_arr,(150,150,3))       # to resize image  (height,width,pixel)   pixel= color image(RGB - red,green,blue)
    flat_data_arr.append(img_resize.flatten())        # to make 1D(flatten) and append
    target_arr.append(categories.index(i))      # index of i=0 if cat and index of i=1 if dog
  print('Loading completed',i)

Loading categories....
Loading completed Cat
Loading categories....
Loading completed Dog


In [ ]:
flat_data=np.array(flat_data_arr)
target_arr=np.array(target_arr)
df=pd.DataFrame(flat_data)
df

0         1         2         3         4         5         6      \
0    0.567769  0.512867  0.461886  0.573767  0.518865  0.467885  0.545760   
1    0.654589  0.092548  0.203156  0.643521  0.093398  0.199501  0.633144   
2    0.869272  0.873193  0.853585  0.873435  0.877356  0.857749  0.875278   
3    0.145156  0.152999  0.133391  0.140967  0.148810  0.129202  0.139563   
4    0.281699  0.995425  0.999346  0.281699  0.995425  0.999346  0.281699   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.078935  0.086778  0.075013  0.082741  0.090585  0.078820  0.097564   
149  0.567795  0.743022  0.536629  0.576316  0.754119  0.562781  0.532521   
150  0.342631  0.439104  0.279701  0.275549  0.388488  0.238657  0.286709   
151  0.003922  0.003922  0.003922  0.003922  0.003922  0.003922  0.003922   
152  0.048783  0.046052  0.040591  0.040040  0.037309  0.031848  0.039114   

        7         8         9      ...     67490     67491     67492  \
0    0.490858  0.439877  0.557858  ...  0.521950  0.728231  0.660557   
1    0.093794  0.195976  0.627333  ...  0.196421  0.644119  0.166650   
2    0.879199  0.859591  0.869854  ...  0.850214  0.838799  0.828248   
3    0.147406  0.127798  0.142803  ...  0.134194  0.233680  0.245358   
4    0.995425  0.999346  0.281569  ...  0.975382  0.677381  0.997971   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.105407  0.093643  0.116938  ...  0.505489  0.518806  0.530571   
149  0.711565  0.525503  0.521763  ...  0.192060  0.292546  0.214115   
150  0.418971  0.200387  0.280261  ...  0.972995  0.987786  0.964669   
151  0.003922  0.003922  0.003922  ...  0.003922  0.003922  0.003922   
152  0.036383  0.030922  0.042620  ...  0.049052  0.243144  0.293808   

        67493     67494     67495     67496     67497     67498     67499  
0    0.600644  0.698120  0.629841  0.567903  0.732229  0.653866  0.600209  
1    0.215340  0.686256  0.145864  0.234624  0.698753  0.139866  0.235372  
2    0.816542  0.845064  0.832109  0.811390  0.850880  0.828851  0.824736  
3    0.212141  0.191619  0.201387  0.160922  0.132091  0.123605  0.087677  
4    0.993252  0.674711  0.988845  0.975943  0.709319  0.992365  0.986100  
..        ...       ...       ...       ...       ...       ...       ...  
148  0.550179  0.496733  0.508497  0.528105  0.494269  0.506033  0.525641  
149  0.210193  0.233386  0.154954  0.151033  0.266417  0.187986  0.184064  
150  0.972176  0.988084  0.964348  0.967420  0.984593  0.961269  0.961172  
151  0.003922  0.003922  0.003922  0.003922  0.003922  0.003922  0.003922  
152  0.060043  0.284722  0.342444  0.076628  0.302048  0.327798  0.056587  

[153 rows x 67500 columns]

In [ ]:
df.shape

(153, 67500)

In [ ]:
df['Target']=target_arr     # to add output column
df.shape

(153, 67501)

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('Accuracy Score:',accuracy_score(y_test,y_pred))

Accuracy Score: 0.5483870967741935


In [ ]:
path1='/content/drive/MyDrive/pexels-pixabay-45201.jpg'
img=imread(path1)    # to read image
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])

In [ ]:
path1='/content/drive/MyDrive/pexels-lkloeppel-1307630.jpg'
img=imread(path1)    # to read image
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])

In [ ]:
p='/content/dog3.jpg'
img=imread(p)    # to read image
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])